set nohlsearch
set paste
set autoindent                    "Preserve current indent on new lines
set backspace=indent,eol,start    "Make backspaces delete sensibly
set tabstop=4                     "Indentation levels every four columns
set expandtab                     "Convert all tabs typed to spaces
set shiftwidth=4                  "Indent/outdent by four columns
set shiftround                    "Indent/outdent to nearest tabstop
set matchpairs+=<:>               "Allow % to bounce between angles too
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
syntax enable
set smartindent
syntax on
filetype plugin indent on
